services:
  - type: web
    name: clinton-portfolio
    env: static
    buildCommand: true
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html